import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f3ff",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed-variant": "#004c6e",
        "tertiary-container": "#bf0f3c",
        "secondary-container": "#39b8fd",
        "surface-container": "#eaedff",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#004666",
        "inverse-on-surface": "#eef0ff",
        "inverse-surface": "#283044",
        "tertiary-fixed-dim": "#ffb2b7",
        secondary: "#006591",
        "on-secondary-fixed": "#001e2f",
        background: "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "secondary-fixed-dim": "#89ceff",
        "on-surface": "#131b2e",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "on-tertiary-container": "#ffd0d2",
        "primary-fixed-dim": "#c3c0ff",
        error: "#ba1a1a",
        outline: "#777587",
        "surface-container-high": "#e2e7ff",
        primary: "#3525cd",
        "surface-dim": "#d2d9f4",
        "on-background": "#131b2e",
        tertiary: "#95002b",
        "on-tertiary-fixed-variant": "#92002a",
        "on-primary": "#ffffff",
        surface: "#faf8ff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#c9e6ff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdadb",
        "on-tertiary-fixed": "#40000d",
        "on-secondary": "#ffffff",
        "surface-variant": "#dae2fd",
        "surface-bright": "#faf8ff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "primary-fixed": "#e2dfff",
        "on-primary-container": "#dad7ff",
        "primary-container": "#4f46e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-padding-desktop": "8rem",
        "stack-lg": "2rem",
        gutter: "1.5rem",
        "section-padding-mobile": "4rem",
        "container-max": "1280px",
        "stack-md": "1rem",
        "stack-sm": "0.5rem",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "display-lg": [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "800" },
        ],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
